### ISSUE TITLE
Showsql need an arguments 

### ISSUE THREAD

**Issue by baselrabia** [dietercoopman/laravel-showsql#1]
Hello Dieter 
I'm trying the package and this happens, am I doing something wrong !!

`        $res = Reservation::showSql()->get();
`

> "message": "Too few arguments to function Illuminate\\Database\\Query\\Builder::Dietercoopman\\Showsql\\{closure}(), 0 passed in /home/captain-x/safa/yarvel/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 114 and exactly 1 expected",

**Comment by baselrabia** [comment]
"php": "^7.3|^8.0",
"laravel/framework": "^8.54",

**Comment by dietercoopman** [comment]
@baselrabia that's a bug , I'll fix it right away ...

For the time being you can use 

```
Reservation::showSql(function(string $sql){
        echo($sql);
    })->get();
```

**Comment by dietercoopman** [comment]
@baselrabia 🥳  The bug has been fixed , thx for your feedback 

Have a nice day !

**Comment by baselrabia** [comment]
@dietercoopman Thanks man, Have a nice one too  🤩 🥳
