### ISSUE TITLE
Incompatibility with Laravel ide-helper.

### ISSUE THREAD

**Issue by Temepest74** [dietercoopman/laravel-showsql#5]
As you may be aware, [this](https://github.com/barryvdh/laravel-ide-helper) packages is widely use.
When I run ide-helper commands I get the following output
![image](https://user-images.githubusercontent.com/28103890/146383462-c2071581-3216-4a09-88cc-8f900225cec4.png)

I highly advise adding support for this package.

**Comment by dietercoopman** [comment]
I will take a look into it , thx for the feedback 👍

**Comment by dietercoopman** [comment]
Hi @Temepest74 this issue has been fixed.

Have a nice and thx for the feedback

**Comment by Temepest74** [comment]
@dietercoopman Thank you
